name: Docker Image CI

on:
  push:

  tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKEPASS }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERUSER }}/client
      -
        name: Build and push nginx
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERUSER }}/nginx
      -
        name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERUSER }}/server
      -
        name: Build and push worker
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERUSER }}/worker
