name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      env:
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKEPASS }}
      run: |
        echo "${{ secrets.DOCKERPASS }}" | docker login -u "${{ secrets.DOCKERUSER }}" --password-stdin
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t rishabchauhan/client ./client && docker push rishabchauhan/client
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t rishabchauhan/nginx ./nginx && docker push rishabchauhan/nginx
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t rishabchauhan/server ./server && docker push rishabchauhan/server
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t rishabchauhan/worker ./worker && docker push rishabchauhan/worker
